'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

export type Lang = 'en' | 'pt'

export const translations = {
  en: {
    home: 'Menu',
    search: 'Search',
    cart: 'Cart',
    profile: 'Profile',
    menuLabel: 'Menu',
    ourDishes: 'Our Dishes',
    searchPlaceholder: 'Search dishes...',
    all: 'All',
    featured: 'Most ordered',
    featuredSubtitle: 'Customer favorites',
    homePromoCarouselAria: 'Promotions',
    homePromoDotsAria: 'Slide',
    fullMenu: 'Full Menu',
    searchResults: 'Results',
    noItemsFound: 'No items found',
    noItemsHint: 'Try searching for a different dish or category',
    addToCart: 'Add',
    unavailable: 'Unavailable',
    myCart: 'My Cart',
    emptyCart: 'Your cart is empty',
    emptyCartHint: 'Add items from the menu to place your order.',
    viewMenu: 'View Menu',
    clearAll: 'Clear all',
    items: 'items',
    item: 'item',
    total: 'Total',
    cartSubtotal: 'Subtotal',
    cartDiscount: 'Discount',
    cartPromoCodeLabel: 'Promo code',
    cartPromoApply: 'Apply',
    cartPromoInvalid: 'Invalid or inactive promo code.',
    cartPromoApplied: 'Promotion applied',
    cartPromoStoreOff: 'Store promotion on this order',
    placeOrder: 'Place Order',
    currency: '$',
    profileTitle: 'Profile',
    visitor: 'Visitor',
    welcomeMsg: 'Welcome to our menu!',
    myCartLink: 'My Cart',
    appVersion: 'Digital Menu v1.0',
    profileSignIn: 'Sign in',
    profileCreateAccount: 'Create account',
    profileSignedInHint: 'You are signed in.',
    profileAuthNoAccount: "Don't have an account?",
    profileAuthHasAccount: 'Already have an account?',
    profileFullName: 'Full name',
    profilePhone: 'Phone',
    profileEmail: 'Email',
    profilePassword: 'Password',
    profileShowPassword: 'Show password',
    profileHidePassword: 'Hide password',
    profileSigningIn: 'Signing in...',
    profileCreating: 'Creating...',
    profileAuthInvalid: 'Invalid email or password.',
    profileAuthAdminBlocked: 'Staff accounts use the administrative login.',
    profileAuthCreatedConfirmEmail:
      'Account created. If email confirmation is required, open the link we sent, then sign in.',
    registerSmsConsentLine1:
      'Yes, I agree to receive transactional SMS messages from Cadu Cakes & Lanches regarding my order, including order confirmations, status updates, delivery notifications, and cancellations.',
    registerSmsConsentLine2: 'Message frequency varies. Message and data rates may apply.',
    registerSmsConsentLine3: 'Reply STOP to opt out or HELP for assistance.',
    registerSmsConsentRequired: 'You must accept the SMS terms above to continue.',
    registerIntroBlurb:
      'Save your name, phone and email so you do not have to enter them on every order.',
    registerPreferencesTitle: 'Other preferences',
    registerPrefEmailLabel:
      'I want to receive emails with updates about my orders.',
    registerPrefCardLabel:
      'I authorize saving my card for future purchases when PayPal offers that option securely — you can confirm again at checkout.',
    checkoutTitle: 'Your details',
    checkoutIntro:
      'Enter your information to complete the order. With an account we save it for next time.',
    checkoutGuestContactTitle: 'Contact details',
    checkoutFulfillmentTitle: 'How do you want to receive your order?',
    checkoutTakeOut: 'Take out',
    checkoutDelivery: 'Delivery',
    checkoutTakeOutHint: 'You can pick up your order at the store.',
    checkoutDeliveryAddressLabel: 'Delivery address',
    checkoutDeliveryLocationLabel: 'City / location',
    checkoutDeliveryAddressPlaceholder: 'Street, number, apartment, city, zip code',
    checkoutDeliveryAddressSaved: 'Using your saved delivery address from your profile.',
    checkoutEditDelivery: 'Edit',
    checkoutCancelDeliveryEdit: 'Cancel',
    checkoutEmailHelp: 'Used for payment receipts (PayPal).',
    checkoutConnected: 'Signed in',
    checkoutGuestSavePrompt: 'Want to save your details for next orders?',
    checkoutCreateAccount: 'Create account',
    checkoutAlreadyHaveAccount: 'I already have an account',
    checkoutContinue: 'Continue to payment',
    checkoutSaving: 'Saving...',
    checkoutLoading: 'Loading...',
    loadingMenu: 'Loading menu...',
    loadingSearch: 'Searching...',
    loadingProduct: 'Loading product...',
    loadingProfile: 'Loading profile...',
    loadingAdmin: 'Loading admin...',
    loadingOrders: 'Loading orders...',
    checkoutErrNome: 'Enter your full name (at least 2 characters).',
    checkoutErrPhone: 'Enter a valid phone number (at least 8 digits).',
    checkoutErrEmail: 'Enter a valid email address.',
    checkoutErrAddress: 'Enter a valid delivery address (at least 6 characters).',
    checkoutOrderPrefsTitle: 'Preferences for this order',
    checkoutSelectAll: 'Select all',
    checkoutPrefsAllOptional: 'All options below are optional.',
    checkoutCommPrefs: 'Communication and card',
    checkoutPrefSms: 'Receive SMS with order updates.',
    checkoutBackAria: 'Back to cart',
    paymentTitle: 'Payment',
    paymentOrderSummary: 'Order summary',
    paymentSubtotal: 'Subtotal',
    paymentDiscount: 'Discount',
    paymentDeliveryFee: 'Delivery fee',
    paymentPromoCodeLabel: 'Promo code',
    paymentObsLabel: 'Note:',
    paymentEditDetails: 'Edit details',
    paymentCardLoading: 'Loading payment options...',
    paymentCardUnavailable: "Card payment isn't available here. Choose PayPal above.",
    paymentMethodCard: 'Card',
    paymentMethodPayPal: 'PayPal',
    paymentCardDetailsTitle: 'Card details',
    paymentCardIntro:
      'Your card details are processed by PayPal. We do not store your card on our servers. Below you can opt in to save your card for future purchases when we enable that feature.',
    paymentSaveCardCheckbox:
      'Save this card for future purchases (I confirm my intent on this payment).',
    paymentPayConfirm: 'Pay & confirm',
    paymentProcessing: 'Processing…',
    paymentPaypalSecureTitle: 'Pay securely with PayPal',
    paymentPaypalIntro:
      'Paying with your PayPal wallet does not use the save-card option for typed cards. We still do not store card data on our servers.',
    paymentCheckoutLoading: 'Loading checkout…',
    paymentConfirmedTitle: 'Payment confirmed',
    paymentConfirmedSubtitle: 'Your order was placed successfully.',
    paymentFailedNotCompleted:
      'Payment was not completed. Your card may have been declined—try another card or PayPal.',
    paymentOrderNumberLabel: 'Order number',
    paymentBackToMenu: 'Back to menu',
    paymentBackToCart: 'Back to cart',
    paymentEmptyCart: 'Your cart is empty.',
    paymentHeaderBackAria: 'Back',
    searchTitle: 'Search',
    searchPagePlaceholder: 'Dishes, categories...',
    results: 'Results for',
    noResults: 'No results',
    noResultsHint: 'Try different keywords',
    recentSearches: 'Recent Searches',
    adminTitle: 'Menu Admin',
    adminPanel: 'Panel',
    tabItems: 'Items',
    tabCategories: 'Categories',
    newItem: 'New Item',
    editItem: 'Edit Item',
    newCategory: 'New Category',
    editCategory: 'Edit Category',
    fieldName: 'Name *',
    fieldDesc: 'Description',
    fieldPrice: 'Price (USD) *',
    fieldImage: 'Product Image',
    fieldCategory: 'Category',
    fieldOrder: 'Order',
    fieldAvailable: 'Available',
    fieldFeatured: 'Featured',
    fieldActive: 'Active',
    fieldIcon: 'Icon (emoji)',
    noCategory: 'No category',
    placeholderName: 'Ex: Margherita Pizza',
    placeholderDesc: 'Ingredients, details...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Save',
    saving: 'Saving...',
    logout: 'Logout',
    deleteItemConfirm: 'Delete this menu item?',
    deleteCatConfirm: 'Delete this category? Items will become uncategorized.',
    noItems: 'No items yet',
    noItemsHintAdmin: 'Add your first menu item.',
    addItem: 'Add Item',
    noCategories: 'No categories',
    noCategoriesHint: 'Create categories to organize the menu.',
    addCategory: 'Add Category',
    available: 'Available',
    hidden: 'Hidden',
    active: 'Active',
    inactive: 'Inactive',
    order: 'Order:',
    adminFilterSearch: 'Search',
    adminFilterSearchPlaceholder: 'Name or description…',
    adminFilterAvailability: 'Availability',
    adminFilterFeatured: 'Featured',
    adminFilterYesOnly: 'Featured only',
    adminFilterNoOnly: 'Not featured',
    adminClearFilters: 'Clear filters',
    adminNoFilterResults: 'No items match these filters.',
    adminShowingCount: 'Showing {n} of {total}',
    kitchenTitle: 'Kitchen',
    kitchenPipelineTitle: 'Order pipeline',
    kitchenColNew: 'New orders',
    kitchenColPrep: 'Preparing',
    kitchenColDelivered: 'Delivered',
    kitchenTodayNote: 'Showing today’s orders (San Francisco time).',
    kitchenClearDelivered: 'Clear list',
    kitchenClearDeliveredHint:
      'Hides delivered orders in this column on this device. Nothing is deleted from the database. Hidden list resets the next SF day.',
    kitchenShowDeliveredAgain: 'Show delivered',
    kitchenNoOrdersToday: 'No orders for today (San Francisco).',
    kitchenHiddenCount: '{n} hidden',
    promoNavLink: 'Promotions',
    promoBackAdmin: 'Back to panel',
    promoPageTitle: 'Promotions',
    promoPageSubtitle: 'Minimum order discount, promo codes, and category discounts.',
    promoAdd: 'New promotion',
    promoColName: 'Name',
    promoColType: 'Type',
    promoColDiscount: 'Discount',
    promoColDetail: 'Rule',
    promoColActive: 'Active',
    promoColActions: 'Actions',
    promoTipoSubtotal: 'Min. order → % off',
    promoTipoCodigo: 'Promo code',
    promoTipoCategoria: 'Category % off',
    promoTipoDeliveryGratis: 'Free delivery over minimum',
    promoTipoCompreGanhe: 'Buy X get Y free',
    promoEdit: 'Edit',
    promoDelete: 'Delete',
    promoDeleteConfirm: 'Delete this promotion?',
    promoModalNew: 'New promotion',
    promoModalEdit: 'Edit promotion',
    promoFieldName: 'Internal name',
    promoFieldBannerImage: 'Home banner image (optional)',
    promoFieldBannerOrder: 'Banner order in carousel',
    promoBannerImageHint: 'Shown on the menu home. Active promos with an image appear first by order.',
    promoFieldDisplayName: 'Customer-facing name (optional)',
    promoFieldDisplayNameHint: 'Shown in cart and checkout. If empty, the internal name is used.',
    promoFieldType: 'Promotion type',
    promoFieldPercent: 'Discount (%)',
    promoFieldMinSubtotal: 'Minimum cart subtotal (USD)',
    promoFieldCode: 'Promo code',
    promoFieldCodeMinSubtotal: 'Minimum cart subtotal for this code (USD, optional)',
    promoDeliveryFeeTitle: 'Delivery fee',
    promoDeliveryFeeHint: 'Applied automatically when the customer chooses delivery.',
    promoDeliveryFeeLabel: 'Delivery fee amount (USD)',
    promoDeliveryFeeSave: 'Save fee',
    promoCouponCategories: 'Valid categories (optional)',
    promoCouponProducts: 'Valid products (optional)',
    promoSearchProducts: 'Search products...',
    promoNoProductsFound: 'No products found for this search.',
    promoCouponScopeHint:
      'Leave both empty to apply the code to the whole cart. If you select categories and/or products, the discount applies only to those lines (OR logic). Minimum order compares to that eligible amount.',
    promoFieldCategory: 'Category',
    promoSelectProduct: 'Select product…',
    promoBuyXItem: 'Buy this product',
    promoBuyXQty: 'Buy quantity (X)',
    promoGetYItem: 'Free product',
    promoGetYQty: 'Free quantity (Y)',
    promoBuyXGetYLabel: 'Buy X get Y',
    promoDeliveryFreeLabel: 'Free delivery',
    promoFieldActive: 'Active',
    promoFieldValidFrom: 'Valid from (optional)',
    promoFieldValidTo: 'Valid until (optional)',
    promoSave: 'Save',
    promoCancel: 'Cancel',
    promoEmpty: 'No promotions yet. Create one to use at checkout later.',
    promoErrName: 'Enter a name.',
    promoErrPercent: 'Enter a valid percentage (1–100).',
    promoErrMinSubtotal: 'Enter a minimum subtotal greater than zero.',
    promoErrCode: 'Enter a promo code.',
    promoErrCategory: 'Choose a category.',
    promoErrBuyXGetYItems: 'Select both products (buy and free).',
    promoErrBuyXGetYQty: 'Enter valid quantities for buy and free items.',
    promoErrDeliveryFee: 'Enter a valid delivery fee (0 or more).',
    promoErrCodeDuplicate: 'This promo code is already in use.',
    promoSelectCategory: 'Select…',
    uploadPhoto: 'Tap to add photo',
    uploadHint: 'JPG, PNG or WebP — max 5MB',
    uploadError: 'Upload failed. Please try again.',
    fileTooLarge: 'Image too large. Max: 5MB.',
    invalidFile: 'Please select a valid image file.',
  },
  pt: {
    home: 'Cardapio',
    search: 'Busca',
    cart: 'Carrinho',
    profile: 'Perfil',
    menuLabel: 'Cardapio',
    ourDishes: 'Nossos Pratos',
    searchPlaceholder: 'Buscar pratos...',
    all: 'Todas',
    featured: 'Mais pedidos',
    featuredSubtitle: 'Favoritos dos clientes',
    homePromoCarouselAria: 'Promoções',
    homePromoDotsAria: 'Slides',
    fullMenu: 'Cardapio Completo',
    searchResults: 'Resultados',
    noItemsFound: 'Nenhum item encontrado',
    noItemsHint: 'Tente buscar por outro prato ou categoria',
    addToCart: 'Adicionar',
    unavailable: 'Indisponivel',
    myCart: 'Carrinho',
    emptyCart: 'Carrinho vazio',
    emptyCartHint: 'Adicione itens do cardapio para fazer seu pedido.',
    viewMenu: 'Ver cardapio',
    clearAll: 'Limpar tudo',
    items: 'itens',
    item: 'item',
    total: 'Total',
    cartSubtotal: 'Subtotal',
    cartDiscount: 'Desconto',
    cartPromoCodeLabel: 'Código promocional',
    cartPromoApply: 'Aplicar',
    cartPromoInvalid: 'Código inválido ou inativo.',
    cartPromoApplied: 'Promoção aplicada',
    cartPromoStoreOff: 'Promoção da loja neste pedido',
    placeOrder: 'Finalizar Pedido',
    currency: '$',
    profileTitle: 'Perfil',
    visitor: 'Visitante',
    welcomeMsg: 'Bem-vindo ao nosso cardapio!',
    myCartLink: 'Meu Carrinho',
    appVersion: 'Cardapio Digital v1.0',
    profileSignIn: 'Entrar',
    profileCreateAccount: 'Criar conta',
    profileSignedInHint: 'Sua conta esta ativa neste aparelho.',
    profileAuthNoAccount: 'Nao tem conta?',
    profileAuthHasAccount: 'Ja tem conta?',
    profileFullName: 'Nome completo',
    profilePhone: 'Telefone',
    profileEmail: 'E-mail',
    profilePassword: 'Senha',
    profileShowPassword: 'Mostrar senha',
    profileHidePassword: 'Ocultar senha',
    profileSigningIn: 'Entrando...',
    profileCreating: 'Criando...',
    profileAuthInvalid: 'E-mail ou senha invalidos.',
    profileAuthAdminBlocked: 'Para equipe, use a area administrativa.',
    profileAuthCreatedConfirmEmail:
      'Conta criada. Se for preciso confirmar o e-mail, abra o link recebido e depois entre.',
    registerSmsConsentLine1:
      'Sim, concordo em receber mensagens SMS transacionais da Cadu Cakes & Lanches referentes ao meu pedido, incluindo confirmações, atualizações de status, notificações de entrega e cancelamentos.',
    registerSmsConsentLine2:
      'A frequência das mensagens varia. Tarifas de mensagens e dados podem ser aplicadas.',
    registerSmsConsentLine3: 'Responda STOP para cancelar o recebimento ou HELP para obter ajuda.',
    registerSmsConsentRequired: 'Aceite os termos de SMS acima para continuar.',
    registerIntroBlurb: 'Guarde seu nome, telefone e e-mail para não repetir em cada pedido.',
    registerPreferencesTitle: 'Outras preferências',
    registerPrefEmailLabel: 'Quero receber e-mails com atualizações dos meus pedidos.',
    registerPrefCardLabel:
      'Autorizo salvar meu cartão para compras futuras, quando o PayPal oferecer essa opção de forma segura — na hora do pagamento você poderá confirmar de novo.',
    checkoutTitle: 'Seus dados',
    checkoutIntro:
      'Informe seus dados para concluir o pedido. Com uma conta, guardamos para a próxima vez.',
    checkoutGuestContactTitle: 'Dados de contato',
    checkoutFulfillmentTitle: 'Como você quer receber seu pedido?',
    checkoutTakeOut: 'Retirada',
    checkoutDelivery: 'Entrega',
    checkoutTakeOutHint: 'Você poderá retirar seu pedido na loja.',
    checkoutDeliveryAddressLabel: 'Endereço de entrega',
    checkoutDeliveryLocationLabel: 'Cidade / localidade',
    checkoutDeliveryAddressPlaceholder: 'Rua, número, complemento, cidade e CEP',
    checkoutDeliveryAddressSaved: 'Usando o endereço de entrega já salvo no seu perfil.',
    checkoutEditDelivery: 'Editar',
    checkoutCancelDeliveryEdit: 'Cancelar',
    checkoutEmailHelp: 'Usado no comprovante de pagamento (PayPal).',
    checkoutConnected: 'Conta conectada',
    checkoutGuestSavePrompt: 'Quer guardar seus dados para os próximos pedidos?',
    checkoutCreateAccount: 'Criar conta',
    checkoutAlreadyHaveAccount: 'Já tenho conta',
    checkoutContinue: 'Continuar para pagamento',
    checkoutSaving: 'Salvando...',
    checkoutLoading: 'Carregando...',
    loadingMenu: 'Carregando cardápio...',
    loadingSearch: 'Carregando...',
    loadingProduct: 'Carregando produto...',
    loadingProfile: 'Carregando perfil...',
    loadingAdmin: 'Carregando painel...',
    loadingOrders: 'Carregando pedidos...',
    checkoutErrNome: 'Informe seu nome completo (mínimo 2 letras).',
    checkoutErrPhone: 'Informe um telefone válido (mínimo 8 dígitos).',
    checkoutErrEmail: 'Informe um e-mail válido.',
    checkoutErrAddress: 'Informe um endereço de entrega válido (mínimo 6 caracteres).',
    checkoutOrderPrefsTitle: 'Preferências deste pedido',
    checkoutSelectAll: 'Marcar todos',
    checkoutPrefsAllOptional: 'Todas as opções abaixo são opcionais.',
    checkoutCommPrefs: 'Comunicação e cartão',
    checkoutPrefSms: 'Receber SMS com atualizações do pedido.',
    checkoutBackAria: 'Voltar ao carrinho',
    paymentTitle: 'Pagamento',
    paymentOrderSummary: 'Resumo do pedido',
    paymentSubtotal: 'Subtotal',
    paymentDiscount: 'Desconto',
    paymentDeliveryFee: 'Taxa de entrega',
    paymentPromoCodeLabel: 'Código promocional',
    paymentObsLabel: 'Obs.:',
    paymentEditDetails: 'Editar dados',
    paymentCardLoading: 'Carregando formas de pagamento...',
    paymentCardUnavailable: 'Pagamento com cartão não está disponível. Toque em PayPal acima.',
    paymentMethodCard: 'Cartão',
    paymentMethodPayPal: 'PayPal',
    paymentCardDetailsTitle: 'Dados do cartão',
    paymentCardIntro:
      'Os dados do cartão são processados pelo PayPal. Ainda não armazenamos o cartão no nosso sistema. Abaixo você pode indicar se deseja salvar para compras futuras quando ativarmos essa opção.',
    paymentSaveCardCheckbox:
      'Salvar este cartão para próximas compras (confirmo minha intenção neste pagamento).',
    paymentPayConfirm: 'Pagar e confirmar',
    paymentProcessing: 'Processando…',
    paymentPaypalSecureTitle: 'Pagar com segurança pelo PayPal',
    paymentPaypalIntro:
      'Pagamento com a carteira PayPal não usa a opção de salvar cartão digitado. O cartão também não fica armazenado em nossos servidores.',
    paymentCheckoutLoading: 'Carregando checkout…',
    paymentConfirmedTitle: 'Pagamento confirmado',
    paymentConfirmedSubtitle: 'Sua ordem foi gerada com sucesso.',
    paymentFailedNotCompleted:
      'O pagamento não foi concluído. O cartão pode ter sido recusado—tente outro cartão ou PayPal.',
    paymentOrderNumberLabel: 'Número da ordem',
    paymentBackToMenu: 'Voltar ao cardápio',
    paymentBackToCart: 'Voltar ao carrinho',
    paymentEmptyCart: 'Seu carrinho está vazio.',
    paymentHeaderBackAria: 'Voltar',
    searchTitle: 'Buscar',
    searchPagePlaceholder: 'Pratos, categorias...',
    results: 'Resultados para',
    noResults: 'Sem resultados',
    noResultsHint: 'Tente palavras diferentes',
    recentSearches: 'Buscas Recentes',
    adminTitle: 'Admin Cardapio',
    adminPanel: 'Painel',
    tabItems: 'Itens',
    tabCategories: 'Categorias',
    newItem: 'Novo Item',
    editItem: 'Editar Item',
    newCategory: 'Nova Categoria',
    editCategory: 'Editar Categoria',
    fieldName: 'Nome *',
    fieldDesc: 'Descricao',
    fieldPrice: 'Preco (USD) *',
    fieldImage: 'Imagem do Produto',
    fieldCategory: 'Categoria',
    fieldOrder: 'Ordem',
    fieldAvailable: 'Disponivel',
    fieldFeatured: 'Destaque',
    fieldActive: 'Ativa',
    fieldIcon: 'Icone (emoji)',
    noCategory: 'Sem categoria',
    placeholderName: 'Ex: Pizza Margherita',
    placeholderDesc: 'Ingredientes, detalhes...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Salvar',
    saving: 'Salvando...',
    logout: 'Sair',
    deleteItemConfirm: 'Excluir este item do cardapio?',
    deleteCatConfirm: 'Excluir esta categoria? Os itens associados ficarao sem categoria.',
    noItems: 'Nenhum item cadastrado',
    noItemsHintAdmin: 'Crie o primeiro item do seu cardapio.',
    addItem: 'Adicionar Item',
    noCategories: 'Nenhuma categoria',
    noCategoriesHint: 'Crie categorias para organizar o cardapio.',
    addCategory: 'Adicionar Categoria',
    available: 'Disponivel',
    hidden: 'Oculto',
    active: 'Ativa',
    inactive: 'Inativa',
    order: 'Ordem:',
    adminFilterSearch: 'Buscar',
    adminFilterSearchPlaceholder: 'Nome ou descricao…',
    adminFilterAvailability: 'Disponibilidade',
    adminFilterFeatured: 'Destaque',
    adminFilterYesOnly: 'Só em destaque',
    adminFilterNoOnly: 'Sem destaque',
    adminClearFilters: 'Limpar filtros',
    adminNoFilterResults: 'Nenhum item corresponde aos filtros.',
    adminShowingCount: 'Mostrando {n} de {total}',
    kitchenTitle: 'Cozinha',
    kitchenPipelineTitle: 'Pipeline de Ordens',
    kitchenColNew: 'Novas Ordens',
    kitchenColPrep: 'Preparação',
    kitchenColDelivered: 'Entregue',
    kitchenTodayNote: 'Só pedidos do dia (horário São Francisco).',
    kitchenClearDelivered: 'Limpar lista',
    kitchenClearDeliveredHint:
      'Oculta os entregues nesta coluna neste aparelho. Nada é apagado no banco. A lista oculta zera no próximo dia (SF).',
    kitchenShowDeliveredAgain: 'Mostrar entregues',
    kitchenNoOrdersToday: 'Nenhum pedido hoje (São Francisco).',
    kitchenHiddenCount: '{n} oculto(s)',
    promoNavLink: 'Promoções',
    promoBackAdmin: 'Voltar ao painel',
    promoPageTitle: 'Promoções',
    promoPageSubtitle: 'Desconto por pedido mínimo, código promocional e por categoria.',
    promoAdd: 'Nova promoção',
    promoColName: 'Nome',
    promoColType: 'Tipo',
    promoColDiscount: 'Desconto',
    promoColDetail: 'Regra',
    promoColActive: 'Ativa',
    promoColActions: 'Ações',
    promoTipoSubtotal: 'Pedido mínimo → % off',
    promoTipoCodigo: 'Código promocional',
    promoTipoCategoria: 'Desconto por categoria',
    promoTipoDeliveryGratis: 'Frete grátis acima do mínimo',
    promoTipoCompreGanhe: 'Compre X ganhe Y',
    promoEdit: 'Editar',
    promoDelete: 'Excluir',
    promoDeleteConfirm: 'Excluir esta promoção?',
    promoModalNew: 'Nova promoção',
    promoModalEdit: 'Editar promoção',
    promoFieldName: 'Nome interno',
    promoFieldBannerImage: 'Imagem do banner na home (opcional)',
    promoFieldBannerOrder: 'Ordem no carrossel',
    promoBannerImageHint: 'Aparece no cardápio. Promoções ativas com imagem entram na ordem indicada.',
    promoFieldDisplayName: 'Nome para o cliente (opcional)',
    promoFieldDisplayNameHint: 'Aparece no carrinho e no pagamento. Se vazio, usamos o nome interno.',
    promoFieldType: 'Tipo de promoção',
    promoFieldPercent: 'Desconto (%)',
    promoFieldMinSubtotal: 'Subtotal mínimo do carrinho (USD)',
    promoFieldCode: 'Código promocional',
    promoFieldCodeMinSubtotal: 'Subtotal mínimo do carrinho para o código valer (USD, opcional)',
    promoDeliveryFeeTitle: 'Taxa de entrega',
    promoDeliveryFeeHint: 'Aplicada automaticamente quando o cliente escolhe entrega.',
    promoDeliveryFeeLabel: 'Valor da taxa de entrega (USD)',
    promoDeliveryFeeSave: 'Salvar taxa',
    promoCouponCategories: 'Categorias válidas (opcional)',
    promoCouponProducts: 'Produtos válidos (opcional)',
    promoSearchProducts: 'Pesquisar produtos...',
    promoNoProductsFound: 'Nenhum produto encontrado para esta busca.',
    promoCouponScopeHint:
      'Deixe os dois vazios para o código valer no carrinho inteiro. Se marcar categorias e/ou produtos, o desconto vale só nessas linhas (lógica OU). O pedido mínimo considera só o valor elegível.',
    promoFieldCategory: 'Categoria',
    promoSelectProduct: 'Selecione o produto…',
    promoBuyXItem: 'Produto para comprar',
    promoBuyXQty: 'Quantidade para comprar (X)',
    promoGetYItem: 'Produto grátis',
    promoGetYQty: 'Quantidade grátis (Y)',
    promoBuyXGetYLabel: 'Compre X ganhe Y',
    promoDeliveryFreeLabel: 'Frete grátis',
    promoFieldActive: 'Ativa',
    promoFieldValidFrom: 'Válida de (opcional)',
    promoFieldValidTo: 'Válida até (opcional)',
    promoSave: 'Salvar',
    promoCancel: 'Cancelar',
    promoEmpty: 'Nenhuma promoção cadastrada. Crie uma para usar no checkout depois.',
    promoErrName: 'Informe um nome.',
    promoErrPercent: 'Informe um percentual válido (1–100).',
    promoErrMinSubtotal: 'Informe um subtotal mínimo maior que zero.',
    promoErrCode: 'Informe o código promocional.',
    promoErrCategory: 'Escolha uma categoria.',
    promoErrBuyXGetYItems: 'Selecione os dois produtos (compra e grátis).',
    promoErrBuyXGetYQty: 'Informe quantidades válidas para compra e grátis.',
    promoErrDeliveryFee: 'Informe uma taxa de entrega válida (0 ou maior).',
    promoErrCodeDuplicate: 'Este código já está em uso.',
    promoSelectCategory: 'Selecione…',
    uploadPhoto: 'Toque para adicionar foto',
    uploadHint: 'JPG, PNG ou WebP — max. 5MB',
    uploadError: 'Erro ao fazer upload. Tente novamente.',
    fileTooLarge: 'Imagem muito grande. Maximo: 5MB.',
    invalidFile: 'Selecione um arquivo de imagem valido.',
  },
} as const

type Translations = typeof translations.en

interface LangContextType {
  lang: Lang
  t: Translations
  toggleLang: () => void
}

const LangContext = createContext<LangContextType | null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  const toggleLang = () => setLang((l) => (l === 'en' ? 'pt' : 'en'))
  const t = translations[lang] as Translations
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used within LangProvider')
  return ctx
}
