'use client'

import { createContext, useContext, useState, type ReactNode } from 'react'

export type Lang = 'en' | 'pt'

export const translations = {
  en: {
    // Nav
    home: 'Menu',
    search: 'Search',
    cart: 'Cart',
    profile: 'Profile',
    // Home
    menuLabel: 'Menu',
    ourDishes: 'Our Dishes',
    searchPlaceholder: 'Search dishes...',
    all: 'All',
    featured: 'Featured',
    featuredSubtitle: "Chef's picks",
    fullMenu: 'Full Menu',
    searchResults: 'Results',
    noItemsFound: 'No items found',
    noItemsHint: 'Try searching for a different dish or category',
    addToCart: 'Add',
    unavailable: 'Unavailable',
    // Cart
    myCart: 'My Cart',
    emptyCart: 'Your cart is empty',
    emptyCartHint: 'Add items from the menu to place your order.',
    viewMenu: 'View Menu',
    clearAll: 'Clear all',
    items: 'items',
    item: 'item',
    total: 'Total',
    placeOrder: 'Place Order',
    viewCart: 'View cart',
    // Home hero
    heroWelcome: 'Welcome to Cadu',
    heroHeadline: 'The sweetest part of your day.',
    heroKicker: 'Made fresh · order nearby',
    heroSubtitle: 'Cakes, snacks & more — order in a few taps.',
    heroCta: 'View menu',
    heroSpecials: "Today's specials",
    storeName: 'Cadu Cakes & Lanches',
    storeOpen: 'Open',
    storeHours: 'Today until 22:00',
    storeTagline: 'We deliver nearby',
    storeDelivery: 'Pickup & delivery',
    yourBag: 'Your bag',
    preloaderText: 'Preparing your order',
    navHome: 'Home',
    navFeatured: 'Specials',
    navCart: 'Cart',
    searchMenu: 'Search the menu',
    catalogLabel: 'MENU',
    customizeProduct: 'Customize',
    loadingProduct: 'Loading product...',
    optionSize: 'Size',
    optionQuantity: 'Quantity',
    kitchenNote: 'Kitchen note',
    kitchenNotePlaceholder: 'E.g.: no onions, well done...',
    viewFullDetails: 'View full product page →',
    // Price
    currency: '$',
    // Profile
    profileTitle: 'Profile',
    visitor: 'Visitor',
    welcomeMsg: 'Welcome to our menu!',
    myCartLink: 'My Cart',
    adminPanel: 'Admin Panel',
    appVersion: 'Digital Menu v1.3.0',
    login: 'Sign in',
    signup: 'Create account',
    loggedInAs: 'Signed in as',
    myAccount: 'My account',
    signOut: 'Sign out',
    // Orders
    myOrders: 'My orders',
    noOrdersYet: 'No orders yet',
    noOrdersHint: 'Your paid orders will appear here.',
    lookupOrder: 'Look up order',
    lookupOrderHint: 'Enter your order number and email used at checkout.',
    orderNumberLabel: 'Order number',
    orderEmailLabel: 'Email',
    lookupSubmit: 'Find order',
    lookupError: 'Order not found. Check the number and email.',
    orderDetailTitle: 'Order status',
    orderProgress: 'Progress',
    orderItems: 'Items',
    orderStatusNew: 'Order received',
    orderStatusPreparing: 'Preparing',
    orderStatusDelivered: 'Ready / delivered',
    orderNotFound: 'Order not found',
    paymentConfirmed: 'Payment confirmed',
    paymentConfirmedHint: 'Your order was placed successfully.',
    trackOrder: 'Track order',
    backToMenu: 'Back to menu',
    back: 'Back',
    recentOrders: 'Recent orders',
    viewOrder: 'View',
    // Search page
    searchTitle: 'Search',
    searchPagePlaceholder: 'Dishes, categories...',
    results: 'Results for',
    noResults: 'No results',
    noResultsHint: 'Try different keywords',
    recentSearches: 'Recent Searches',
    // Admin
    adminTitle: 'Menu Admin',
    adminPanel: 'Panel',
    tabItems: 'Items',
    tabCategories: 'Categories',
    newItem: 'New Item',
    editItem: 'Edit Item',
    newCategory: 'New Category',
    editCategory: 'Edit Category',
    fieldName: 'Name *',
    fieldDesc: 'Description',
    fieldPrice: 'Price (USD) *',
    fieldImage: 'Product Image',
    fieldCategory: 'Category',
    fieldOrder: 'Order',
    fieldAvailable: 'Available',
    fieldFeatured: 'Featured',
    fieldActive: 'Active',
    fieldIcon: 'Icon (emoji)',
    noCategory: 'No category',
    placeholderName: 'Ex: Margherita Pizza',
    placeholderDesc: 'Ingredients, details...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Save',
    saving: 'Saving...',
    logout: 'Logout',
    deleteItemConfirm: 'Delete this menu item?',
    deleteCatConfirm: 'Delete this category? Items will become uncategorized.',
    noItems: 'No items yet',
    noItemsHintAdmin: 'Add your first menu item.',
    addItem: 'Add Item',
    noCategories: 'No categories',
    noCategoriesHint: 'Create categories to organize the menu.',
    addCategory: 'Add Category',
    available: 'Available',
    hidden: 'Hidden',
    active: 'Active',
    inactive: 'Inactive',
    order: 'Order:',
    uploadPhoto: 'Tap to add photo',
    uploadHint: 'JPG, PNG or WebP — max 5MB',
    uploadError: 'Upload failed. Please try again.',
    fileTooLarge: 'Image too large. Max: 5MB.',
    invalidFile: 'Please select a valid image file.',
    // Checkout
    checkoutTitle: 'Your details',
    checkoutHint: 'We need this information for your order. Create an account to save it for next time.',
    checkoutStepData: 'Details',
    checkoutStepPayment: 'Payment',
    checkoutContinuePayment: 'Continue to payment',
    checkoutSaving: 'Saving...',
    checkoutConnectedAccount: 'Account connected',
    checkoutWantAccount: 'Want to save your details for next orders?',
    checkoutCommunication: 'Updates',
    checkoutSmsUpdates: 'Receive SMS with order updates.',
    checkoutEmailUpdates: 'Receive emails with order updates.',
    checkoutFullName: 'Full name',
    checkoutPhone: 'Phone',
    checkoutEmail: 'Email',
    checkoutEmailLinked: 'Email linked to your account.',
    checkoutFillError: 'Enter name (2+ letters), valid email and phone (8+ digits).',
    checkoutLoading: 'Loading...',
    paymentTitle: 'Payment',
    paymentEditData: 'Edit details',
    paymentCardTitle: 'Credit or debit card',
    paymentSecureNote:
      'Your payment is processed securely by Clover. Card data goes directly to Clover and never passes through our servers.',
    paymentCardNumber: 'Card number',
    paymentCardExpiry: 'Expiry',
    paymentCardCvv: 'CVV',
    paymentCardZip: 'ZIP code',
    paymentZipHint: '5-digit US ZIP code required for card verification.',
    paymentPayConfirm: 'Pay & confirm',
    paymentProcessing: 'Processing...',
    paymentLoading: 'Loading checkout...',
    paymentEmptyCart: 'Your cart is empty.',
    paymentBackToCart: 'Back to cart',
    paymentInitError: 'Could not load the card form.',
    paymentTokenError: 'Could not tokenize the card.',
    paymentCheckCard: 'Check your card details.',
    productDetailTitle: 'Product details',
    productNotFound: 'Product not found.',
    productPrice: 'Price',
    productAddToCart: 'Add to cart',
    productIngredients: 'Ingredients',
    productAllergens: 'Allergens',
    productSizes: 'Sizes',
    productQuantityInfo: 'Quantity',
    comboNotFound: 'Combo not found.',
    comboLoading: 'Loading combo...',
    comboItemDefault: 'Combo item',
    comboNoVariations: 'No variations for this item.',
    comboObservation: 'Combo note',
    comboObservationPlaceholder: 'E.g.: no onion in burger',
    comboFinishAdd: 'Finish and add to cart',
    comboAddToCart: 'Add combo to cart',
    comboSelectionError: 'For "{item}", adjust selections for "{group}".',
    adminLoginTitle: 'Admin area',
    adminLoginSubtitle: 'Manage the restaurant menu',
    adminLoginExclusive: 'Access restricted to restaurant administrators.',
    authCustomerAccount: 'This is a customer account. Use the menu to sign in.',
    authSignIn: 'Sign in',
    authPassword: 'Password',
    authEmail: 'Email',
    ordersKitchenEyebrow: 'Kitchen',
    ordersPipelineTitle: 'Order pipeline',
    ordersLoading: 'Loading orders...',
    ordersEmptyColumn: 'No orders in this stage.',
    ordersColNew: 'New orders',
    ordersColPreparing: 'Preparing',
    ordersColDelivered: 'Delivered',
    ordersPhoneLabel: 'Phone',
    ordersInternalNote: 'Internal note',
    manualOrderTitle: 'Counter order',
    manualOrderNew: 'New order',
    manualOrderViewBoard: 'View board',
    manualOrderSearchPlaceholder: 'Search menu...',
    manualOrderNoResults: 'No items found.',
    manualOrderCartTitle: 'Order',
    manualOrderEmptyCart: 'Add items from the menu.',
    manualOrderSubtotal: 'Subtotal',
    manualOrderTax: 'Tax',
    manualOrderCustomerName: 'Customer name',
    manualOrderCustomerPlaceholder: 'Counter (optional)',
    manualOrderPaymentMethod: 'Payment',
    manualOrderPayCash: 'Cash',
    manualOrderPayCard: 'Card',
    manualOrderSubmit: 'Create order',
    manualOrderSubmitting: 'Creating...',
    manualOrderSubmitError: 'Could not create order.',
    manualOrderSuccess: 'Order created!',
    manualOrderBadge: 'Counter',
    adminHubTitle: 'Operations',
    adminHubOrders: 'Orders',
    adminHubCounter: 'Counter order',
    adminHubCombos: 'Combos',
    adminHubPromos: 'Promotions',
    adminHubBanners: 'Banners',
    adminHubDelivery: 'Delivery',
    adminHubPrint: 'Printing',
    adminHubExtras: 'Extra library',
    adminNavSubtitle: 'Operations panel',
    adminNavOperations: 'Operations',
    adminNavNewOrder: 'New order',
    adminNavOrders: 'Orders',
    adminNavMenu: 'Menu',
    adminNavCombos: 'Combos',
    adminNavPromos: 'Promotions',
    adminNavBanners: 'Banners',
    adminNavDelivery: 'Delivery',
    adminNavPrint: 'Printing',
    adminOpsOverview: 'Overview',
    adminOpsIntro: 'What needs your attention right now.',
    adminOpsViewQueue: 'View queue',
    adminOpsPriority: 'Next priority',
    adminOpsQueueClear: 'Queue under control',
    adminOpsQueueClearHint: 'No active orders waiting for action.',
    adminOpsOpenOrder: 'Open order',
    adminOpsMetrics: 'Active orders summary',
    adminOpsActiveOrders: 'Active orders',
    adminOpsDeliveries: 'deliveries',
    adminOpsInDelivery: 'Delivery',
    adminOpsInDeliveryHint: 'in queue now',
    adminOpsPreparing: 'Preparing',
    adminOpsPreparingHint: 'in kitchen',
    adminOpsQueueValue: 'Queue value',
    adminOpsQueueValueHint: 'operational orders',
    adminOpsFlow: 'Queue flow',
    adminOpsFlowTitle: 'Where orders are',
    authShowPassword: 'Show password',
    authHidePassword: 'Hide password',
    authSigningIn: 'Signing in...',
    authInvalidCredentials: 'Invalid email or password.',
    authUseAdmin: 'For staff, use the admin area.',
    authNoAccount: "Don't have an account?",
    authSignUpLink: 'Sign up',
    authHasAccount: 'Already have an account?',
    authSignInLink: 'Sign in',
    authCreating: 'Creating account...',
    authCreateAccount: 'Create account',
    authAccountCreated:
      'Account created. If email confirmation is required, open the link in your inbox and then sign in.',
    authFullName: 'Full name',
    authPhone: 'Phone',
    authSignupHint: 'Save your name, phone and email so you do not repeat them on every order.',
    authRegister: 'Register',
  },
  pt: {

    // Nav
    home: 'Cardapio',
    search: 'Busca',
    cart: 'Carrinho',
    profile: 'Perfil',
    // Home
    menuLabel: 'Cardapio',
    ourDishes: 'Nossos Pratos',
    searchPlaceholder: 'Buscar pratos...',
    all: 'Todas',
    featured: 'Destaques',
    featuredSubtitle: 'Escolhas da casa',
    fullMenu: 'Cardapio Completo',
    searchResults: 'Resultados',
    noItemsFound: 'Nenhum item encontrado',
    noItemsHint: 'Tente buscar por outro prato ou categoria',
    addToCart: 'Adicionar',
    unavailable: 'Indisponivel',
    // Cart
    myCart: 'Carrinho',
    emptyCart: 'Carrinho vazio',
    emptyCartHint: 'Adicione itens do cardapio para fazer seu pedido.',
    viewMenu: 'Ver cardapio',
    clearAll: 'Limpar tudo',
    items: 'itens',
    item: 'item',
    total: 'Total',
    placeOrder: 'Finalizar Pedido',
    viewCart: 'Ver carrinho',
    // Home hero
    heroWelcome: 'Bem-vindo à Cadu',
    heroHeadline: 'O lado mais gostoso do seu dia.',
    heroKicker: 'Feito na hora · peça pertinho',
    heroSubtitle: 'Bolos, lanches e mais — peça em poucos toques.',
    heroCta: 'Ver cardápio',
    heroSpecials: 'Destaques de hoje',
    storeName: 'Cadu Cakes & Lanches',
    storeOpen: 'Aberto',
    storeHours: 'Hoje até 22:00',
    storeTagline: 'Entregamos pertinho de você',
    storeDelivery: 'Retirada e entrega',
    yourBag: 'Sua sacola',
    preloaderText: 'Preparando seu pedido',
    navHome: 'Início',
    navFeatured: 'Destaques',
    navCart: 'Carrinho',
    searchMenu: 'Buscar no cardápio',
    catalogLabel: 'CARDÁPIO',
    customizeProduct: 'Personalize',
    loadingProduct: 'Carregando produto...',
    optionSize: 'Tamanho',
    optionQuantity: 'Quantidade',
    kitchenNote: 'Observação para a cozinha',
    kitchenNotePlaceholder: 'Ex: sem cebola, ponto da carne...',
    viewFullDetails: 'Ver página completa do produto →',
    // Price
    currency: '$',
    // Profile
    profileTitle: 'Perfil',
    visitor: 'Visitante',
    welcomeMsg: 'Bem-vindo ao nosso cardapio!',
    myCartLink: 'Meu Carrinho',
    adminPanel: 'Painel Admin',
    appVersion: 'Cardápio Digital v1.3.0',
    login: 'Entrar',
    signup: 'Criar conta',
    loggedInAs: 'Conectado como',
    myAccount: 'Minha conta',
    signOut: 'Sair',
    // Orders
    myOrders: 'Meus pedidos',
    noOrdersYet: 'Nenhum pedido ainda',
    noOrdersHint: 'Seus pedidos pagos aparecerão aqui.',
    lookupOrder: 'Consultar pedido',
    lookupOrderHint: 'Informe o número do pedido e o e-mail usado no checkout.',
    orderNumberLabel: 'Número do pedido',
    orderEmailLabel: 'E-mail',
    lookupSubmit: 'Buscar pedido',
    lookupError: 'Pedido não encontrado. Confira número e e-mail.',
    orderDetailTitle: 'Status do pedido',
    orderProgress: 'Andamento',
    orderItems: 'Itens',
    orderStatusNew: 'Pedido recebido',
    orderStatusPreparing: 'Em preparo',
    orderStatusDelivered: 'Pronto / entregue',
    orderNotFound: 'Pedido não encontrado',
    paymentConfirmed: 'Pagamento confirmado',
    paymentConfirmedHint: 'Seu pedido foi registrado com sucesso.',
    trackOrder: 'Acompanhar pedido',
    backToMenu: 'Voltar ao cardápio',
    back: 'Voltar',
    recentOrders: 'Pedidos recentes',
    viewOrder: 'Ver',
    // Search page
    searchTitle: 'Buscar',
    searchPagePlaceholder: 'Pratos, categorias...',
    results: 'Resultados para',
    noResults: 'Sem resultados',
    noResultsHint: 'Tente palavras diferentes',
    recentSearches: 'Buscas Recentes',
    // Admin
    adminTitle: 'Admin Cardapio',
    adminPanel: 'Painel',
    tabItems: 'Itens',
    tabCategories: 'Categorias',
    newItem: 'Novo Item',
    editItem: 'Editar Item',
    newCategory: 'Nova Categoria',
    editCategory: 'Editar Categoria',
    fieldName: 'Nome *',
    fieldDesc: 'Descricao',
    fieldPrice: 'Preco (USD) *',
    fieldImage: 'Imagem do Produto',
    fieldCategory: 'Categoria',
    fieldOrder: 'Ordem',
    fieldAvailable: 'Disponivel',
    fieldFeatured: 'Destaque',
    fieldActive: 'Ativa',
    fieldIcon: 'Icone (emoji)',
    noCategory: 'Sem categoria',
    placeholderName: 'Ex: Pizza Margherita',
    placeholderDesc: 'Ingredientes, detalhes...',
    placeholderPrice: 'Ex: 9.99',
    placeholderIcon: '🍽️',
    save: 'Salvar',
    saving: 'Salvando...',
    logout: 'Sair',
    deleteItemConfirm: 'Excluir este item do cardapio?',
    deleteCatConfirm: 'Excluir esta categoria? Os itens associados ficarao sem categoria.',
    noItems: 'Nenhum item cadastrado',
    noItemsHintAdmin: 'Crie o primeiro item do seu cardapio.',
    addItem: 'Adicionar Item',
    noCategories: 'Nenhuma categoria',
    noCategoriesHint: 'Crie categorias para organizar o cardapio.',
    addCategory: 'Adicionar Categoria',
    available: 'Disponivel',
    hidden: 'Oculto',
    active: 'Ativa',
    inactive: 'Inativa',
    order: 'Ordem:',
    uploadPhoto: 'Toque para adicionar foto',
    uploadHint: 'JPG, PNG ou WebP — max. 5MB',
    uploadError: 'Erro ao fazer upload. Tente novamente.',
    fileTooLarge: 'Imagem muito grande. Maximo: 5MB.',
    invalidFile: 'Selecione um arquivo de imagem valido.',
    // Checkout
    checkoutTitle: 'Seus dados',
    checkoutHint: 'Precisamos dessas informações para o pedido. Crie uma conta para guardar na próxima vez.',
    checkoutStepData: 'Dados',
    checkoutStepPayment: 'Pagamento',
    checkoutContinuePayment: 'Continuar para pagamento',
    checkoutSaving: 'Salvando...',
    checkoutConnectedAccount: 'Conta conectada',
    checkoutWantAccount: 'Quer salvar seus dados para próximos pedidos?',
    checkoutCommunication: 'Comunicação',
    checkoutSmsUpdates: 'Receber SMS com atualizações do pedido.',
    checkoutEmailUpdates: 'Receber e-mails com atualizações do pedido.',
    checkoutFullName: 'Nome completo',
    checkoutPhone: 'Telefone',
    checkoutEmail: 'E-mail',
    checkoutEmailLinked: 'E-mail vinculado à sua conta.',
    checkoutFillError: 'Preencha nome (2+ letras), e-mail válido e telefone (8+ dígitos).',
    checkoutLoading: 'Carregando...',
    paymentTitle: 'Pagamento',
    paymentEditData: 'Editar dados',
    paymentCardTitle: 'Cartão de crédito ou débito',
    paymentSecureNote:
      'Pagamento processado com segurança pela Clover. Os dados do cartão vão direto para a Clover e não passam pelos nossos servidores.',
    paymentCardNumber: 'Número do cartão',
    paymentCardExpiry: 'Validade',
    paymentCardCvv: 'CVV',
    paymentCardZip: 'CEP / ZIP',
    paymentZipHint: 'Informe o ZIP de 5 dígitos (ex: 32801) para verificação do cartão.',
    paymentPayConfirm: 'Pagar e confirmar',
    paymentProcessing: 'Processando...',
    paymentLoading: 'Carregando checkout...',
    paymentEmptyCart: 'Seu carrinho está vazio.',
    paymentBackToCart: 'Voltar ao carrinho',
    paymentInitError: 'Não foi possível carregar o formulário de cartão.',
    paymentTokenError: 'Não foi possível tokenizar o cartão.',
    paymentCheckCard: 'Confira os dados do cartão.',
    productDetailTitle: 'Detalhes do produto',
    productNotFound: 'Produto não encontrado.',
    productPrice: 'Preço',
    productAddToCart: 'Adicionar ao carrinho',
    productIngredients: 'Ingredientes',
    productAllergens: 'Alérgenos',
    productSizes: 'Tamanhos',
    productQuantityInfo: 'Quantidade',
    comboNotFound: 'Combo não encontrado.',
    comboLoading: 'Carregando combo...',
    comboItemDefault: 'Item do combo',
    comboNoVariations: 'Sem variações para este item.',
    comboObservation: 'Observação para o combo',
    comboObservationPlaceholder: 'Ex: sem cebola no lanche',
    comboFinishAdd: 'Concluir e adicionar ao carrinho',
    comboAddToCart: 'Adicionar combo ao carrinho',
    comboSelectionError: 'No item "{item}", ajuste as escolhas de "{group}".',
    adminLoginTitle: 'Área Admin',
    adminLoginSubtitle: 'Gerencie o cardápio do restaurante',
    adminLoginExclusive: 'Acesso exclusivo para administradores do restaurante.',
    authCustomerAccount: 'Esta conta é de cliente. Use o acesso pelo cardápio.',
    authSignIn: 'Entrar',
    authPassword: 'Senha',
    authEmail: 'E-mail',
    ordersKitchenEyebrow: 'Cozinha',
    ordersPipelineTitle: 'Pipeline de Ordens',
    ordersLoading: 'Carregando ordens...',
    ordersEmptyColumn: 'Sem ordens nesta etapa.',
    ordersColNew: 'Novas Ordens',
    ordersColPreparing: 'Preparação',
    ordersColDelivered: 'Entregue',
    ordersPhoneLabel: 'Tel.',
    ordersInternalNote: 'Obs interna',
    manualOrderTitle: 'Pedido balcão',
    manualOrderNew: 'Novo pedido',
    manualOrderViewBoard: 'Ver pipeline',
    manualOrderSearchPlaceholder: 'Buscar no cardápio...',
    manualOrderNoResults: 'Nenhum item encontrado.',
    manualOrderCartTitle: 'Pedido',
    manualOrderEmptyCart: 'Adicione itens do cardápio.',
    manualOrderSubtotal: 'Subtotal',
    manualOrderTax: 'Imposto',
    manualOrderCustomerName: 'Nome do cliente',
    manualOrderCustomerPlaceholder: 'Balcão (opcional)',
    manualOrderPaymentMethod: 'Pagamento',
    manualOrderPayCash: 'Dinheiro',
    manualOrderPayCard: 'Cartão',
    manualOrderSubmit: 'Criar pedido',
    manualOrderSubmitting: 'Criando...',
    manualOrderSubmitError: 'Não foi possível criar o pedido.',
    manualOrderSuccess: 'Pedido criado!',
    manualOrderBadge: 'Balcão',
    adminHubTitle: 'Operação',
    adminHubOrders: 'Ordens',
    adminHubCounter: 'Pedido balcão',
    adminHubCombos: 'Combos',
    adminHubPromos: 'Promoções',
    adminHubBanners: 'Banners',
    adminHubDelivery: 'Entregas',
    adminHubPrint: 'Impressão',
    adminHubExtras: 'Extras',
    adminNavSubtitle: 'Painel operacional',
    adminNavOperations: 'Operações',
    adminNavNewOrder: 'Lançar pedido',
    adminNavOrders: 'Pedidos',
    adminNavMenu: 'Cardápio',
    adminNavCombos: 'Combos',
    adminNavPromos: 'Promoções',
    adminNavBanners: 'Banners',
    adminNavDelivery: 'Entrega',
    adminNavPrint: 'Impressão',
    adminOpsOverview: 'Visão geral',
    adminOpsIntro: 'O que precisa da sua atenção agora.',
    adminOpsViewQueue: 'Ver fila',
    adminOpsPriority: 'Próxima prioridade',
    adminOpsQueueClear: 'Fila sob controle',
    adminOpsQueueClearHint: 'Não há pedidos ativos aguardando ação.',
    adminOpsOpenOrder: 'Abrir pedido',
    adminOpsMetrics: 'Resumo de pedidos ativos',
    adminOpsActiveOrders: 'Pedidos ativos',
    adminOpsDeliveries: 'entregas',
    adminOpsInDelivery: 'Em entrega',
    adminOpsInDeliveryHint: 'na fila agora',
    adminOpsPreparing: 'Preparação',
    adminOpsPreparingHint: 'na cozinha',
    adminOpsQueueValue: 'Valor na fila',
    adminOpsQueueValueHint: 'pedidos operacionais',
    adminOpsFlow: 'Fluxo da fila',
    adminOpsFlowTitle: 'Onde estão os pedidos',
    authShowPassword: 'Mostrar senha',
    authHidePassword: 'Ocultar senha',
    authSigningIn: 'Entrando...',
    authInvalidCredentials: 'E-mail ou senha inválidos.',
    authUseAdmin: 'Para equipe, use a área administrativa.',
    authNoAccount: 'Não tem conta?',
    authSignUpLink: 'Cadastre-se',
    authHasAccount: 'Já tem conta?',
    authSignInLink: 'Entrar',
    authCreating: 'Criando conta...',
    authCreateAccount: 'Criar conta',
    authAccountCreated:
      'Conta criada. Se o projeto exigir confirmação por e-mail, abra o link recebido e depois entre em "Já tenho conta".',
    authFullName: 'Nome completo',
    authPhone: 'Telefone',
    authSignupHint: 'Guarde seu nome, telefone e e-mail para não repetir em cada pedido.',
    authRegister: 'Cadastrar',
  },
} as const

type Translations = typeof translations.en

interface LangContextType {
  lang: Lang
  t: Translations
  toggleLang: () => void
}

const LangContext = createContext<LangContextType | null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  const toggleLang = () => setLang((l) => (l === 'en' ? 'pt' : 'en'))
  const t = translations[lang]
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used within LangProvider')
  return ctx
}
