const STORAGE_IMAGE =
  /^https:\/\/[a-z0-9-]+\.supabase\.co\/storage\/v1\/object\/public\/cardapio-imagens\/[^?#\s]+$/i

/**
 * Smaller copy of a menu photo, generated by Supabase from the original file.
 * The original stays in the bucket. Nothing needs to be uploaded again.
 */
export function cachedMenuImageSrc(src: string | null | undefined) {
  const clean = src?.trim().split('#')[0]?.split('?')[0] ?? ''
  if (!STORAGE_IMAGE.test(clean)) return src?.trim() || ''
  const render = clean.replace('/storage/v1/object/public/', '/storage/v1/render/image/public/')
  return `${render}?width=960&quality=72&format=webp`
}

export function isMenuStorageUrl(src: string) {
  return STORAGE_IMAGE.test(src.trim().split('#')[0]?.split('?')[0] ?? '')
}
