ALTER TABLE public.pedidos
ADD COLUMN IF NOT EXISTS valor_pago NUMERIC(10, 2),
ADD COLUMN IF NOT EXISTS valor_bruto NUMERIC(10, 2),
ADD COLUMN IF NOT EXISTS taxa_paypal NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS taxa_entrega NUMERIC(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC(10, 2);
